name: context
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
  pull_request:

jobs:
  context:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Dump Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "${GITHUB_CONTEXT}"
        git rev-parse HEAD
